import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Slider from "@/components/layout/Slider";
import Navbar from "@/components/layout/Navbar";
import Head from "next/head";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "StreamIO",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Head>
          <link rel="favicon" href="/fav.png" />
          <meta name="description" content="Generated by create next app" />
        </Head>
        <div className="w-full">
          <Navbar />
          <div className="flex flex-1 mt-4">
            <aside className="w-[12%]">
              <Slider />
            </aside>
            <main className=" w-[87%]">{children}</main>
          </div>
        </div>
      </body>
    </html>
  );
}
