import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Slider from "@/components/layout/Slider";
import Navbar from "@/components/layout/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "StreamIO",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="min-h-screen">
          <div>
            <Navbar />
          </div>
          <div className="flex mt-4">
            <div className="w-3/10">
              <Slider />
            </div>
            <div className="w-7/10">{children}</div>
          </div>
        </div>
      </body>
    </html>
  );
}
